// Showing Booking form

document.getElementById('BookNow').onclick = function(){FormFunction() };
function FormFunction(){
  document.getElementById('BookingFormID').style.visibility="visible";
  document.getElementById('BookingFormID').style.opacity="1";
  document.getElementById('BookingFormID').style.top="8%";
}

document.getElementById('CloseForm').onclick = function(){CloseFunction() };
function CloseFunction (){
  document.getElementById('BookingFormID').style.visibility="hidden";
  document.getElementById('BookingFormID').style.opacity="0";
  document.getElementById('BookingFormID').style.top="6%";

}

// Showing Img1
document.getElementById('img1').onclick = function() {showPotoFunction()};
function showPotoFunction () {
  document.getElementById('PhotoTemp').src                    ="Pic/e/11.jpg";
  document.getElementById('WideImgId').style.opacity          =".5";
  document.getElementById('MainFlexBox').style.opacity        =".5";
  document.getElementById('AlbumFlexBox').style.opacity       =".5";
  document.getElementById('FooterId').style.opacity           =".5";
  document.getElementById('ShowImg1').style.visibility        ="visible";
  document.getElementById('ShowImg1').style.opacity           ="1";
  document.getElementById('ShowImg1').style.top               ="20%";
  document.getElementById('RightAngelBTN').style.visibility   ="visible";
  document.getElementById('LeftAngelBTN').style.visibility    ="visible";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility        ="hidden";
  document.getElementById('ShowImg1').style.opacity           ="0";
  document.getElementById('ShowImg1').style.top               ="15%";
  document.getElementById('WideImgId').style.opacity          ="1";
  document.getElementById('MainFlexBox').style.opacity        ="1";
  document.getElementById('AlbumFlexBox').style.opacity       ="1";
  document.getElementById('FooterId').style.opacity           ="1";
  document.getElementById('RightAngelBTN').style.visibility   ="visible";
  document.getElementById('LeftAngelBTN').style.visibility    ="hidden";
}


// Showing img2
document.getElementById('img2').onclick = function() {showPoto2Function()};
function showPoto2Function () {
  document.getElementById('PhotoTemp').src="Pic/e/7.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img3

document.getElementById('img3').onclick = function() {showPoto3Function()};
function showPoto3Function () {
  document.getElementById('PhotoTemp').src="Pic/e/6.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img4
document.getElementById('img4').onclick = function() {showPoto4Function()};
function showPoto4Function () {
  document.getElementById('PhotoTemp').src="Pic/e/4.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img5
document.getElementById('img5').onclick = function() {showPoto5Function()};
function showPoto5Function () {
  document.getElementById('PhotoTemp').src="Pic/e/14.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img6 (8)

document.getElementById('img8').onclick = function() {showPoto8Function()};
function showPoto8Function () {
  document.getElementById('PhotoTemp').src="Pic/e/11.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img7 (9)

document.getElementById('img9').onclick = function() {showPoto9Function()};
function showPoto9Function () {
  document.getElementById('PhotoTemp').src="Pic/e/17.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img8 (10)

document.getElementById('img10').onclick = function() {showPoto10Function()};
function showPoto10Function () {
  document.getElementById('PhotoTemp').src="Pic/e/fox.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img9 (12)

document.getElementById('img12').onclick = function() {showPoto12Function()};
function showPoto12Function () {
  document.getElementById('PhotoTemp').src="Pic/e/5.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img10 (13)

document.getElementById('img13').onclick = function() {showPoto13Function()};
function showPoto13Function () {
  document.getElementById('PhotoTemp').src="Pic/e/18.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img11 (16)

document.getElementById('img16').onclick = function() {showPoto16Function()};
function showPoto16Function () {
  document.getElementById('PhotoTemp').src="Pic/e/18.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img12 (17)

document.getElementById('img17').onclick = function() {showPoto17Function()};
function showPoto17Function () {
  document.getElementById('PhotoTemp').src="Pic/e/4.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img13 (18)

document.getElementById('img18').onclick = function() {showPoto18Function()};
function showPoto18Function () {
  document.getElementById('PhotoTemp').src="Pic/e/16.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img14 (19)

document.getElementById('img19').onclick = function() {showPoto19Function()};
function showPoto19Function () {
  document.getElementById('PhotoTemp').src="Pic/e/19.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img15 (20)

document.getElementById('img20').onclick = function() {showPoto20Function()};
function showPoto20Function () {
  document.getElementById('PhotoTemp').src="Pic/e/3.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img16 (21)

document.getElementById('img21').onclick = function() {showPoto21Function()};
function showPoto21Function () {
  document.getElementById('PhotoTemp').src="Pic/e/8.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}

// Showing Img17 (24)

document.getElementById('img24').onclick = function() {showPoto24Function()};
function showPoto24Function () {
  document.getElementById('PhotoTemp').src="Pic/e/11.jpg";
  document.getElementById('WideImgId').style.opacity=".5";
  document.getElementById('MainFlexBox').style.opacity=".5";
  document.getElementById('AlbumFlexBox').style.opacity=".5";
  document.getElementById('FooterId').style.opacity=".5";
  document.getElementById('ShowImg1').style.visibility="visible";
  document.getElementById('ShowImg1').style.opacity="1";
  document.getElementById('ShowImg1').style.top="20%";
}

document.getElementById('backIcon1').onclick = function (){BackIconOrder ()};
function BackIconOrder (){
  document.getElementById('ShowImg1').style.visibility="hidden";
  document.getElementById('ShowImg1').style.opacity="0";
  document.getElementById('ShowImg1').style.top="15%";
  document.getElementById('WideImgId').style.opacity="1";
  document.getElementById('MainFlexBox').style.opacity="1";
  document.getElementById('AlbumFlexBox').style.opacity="1";
  document.getElementById('FooterId').style.opacity="1";
}
